### ISSUE TITLE
getCurrent returns wrong value with negative currents

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/INA226#3]
The current is calculated by dividing the INA internal current register by 8 (to get the result in mA). Currents might also be negative and this causes an error by 1 LSB with negative numbers.

Line 138 of INA226.cpp should be changed by adding the sign bit (basically adding a 1 to negative numbers).

**Comment by StefanoSperetta** [comment]
See https://stackoverflow.com/questions/39691817/divide-a-signed-integer-by-a-power-of-2 for an explanation of the problem

**Comment by StefanoSperetta** [comment]
@MFvandenBos : can you try if the issue is solved by changing line 138 of INA226.cpp from
    c  >>= 3;
to
    c /= 8;

and re-compiling/uploading the EPS code?

I think this should solve the problem as the integer signed division should be available on the MSP432.

**Comment by MFvandenBos** [comment]
I tested this solution and it works well. fix in c06ca94
